name: SonarCloud

on:
  push:
    branches:
      - main
      - Desarrollo
  pull_request:
    branches:
      - main
      - Desarrollo

jobs:
  build:
    name: SonarCloud .NET Scan
    runs-on: windows-latest  # ✅ compatible con proyectos .NET y Visual Studio

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'  # Cambia si usas .NET 6 o .NET 8

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add tool to PATH
        run: echo "${{ runner.tool_cache }}/dotnet/tools" >> $GITHUB_PATH

      - name: Begin SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          dotnet-sonarscanner begin 
          /k:"Dario12311_MIVET.BE" 
          /o:"dario12311" 
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Build the project
        run: dotnet build

      - name: End SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
