name: SonarCloud

on:
  push:
    branches:
      - main
      - Desarrollo
  pull_request:
    branches:
      - main
      - Desarrollo

jobs:
  build:
    name: SonarCloud
    runs-on: windows-latest  # Usamos Windows porque es más común para proyectos Visual Studio

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'  # Cambia si usas .NET 6 o .NET 8

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: Dario12311
          projectKey: Dario12311_MIVET.BE
          token: ${{ secrets.SONAR_TOKEN }}
